version: "3.9"
services:
  db:
    image: mariadb:10
    restart: always
    env_file:
      - ./docker.env
    ports:
      - "33061:3306"
  back:
    build: ./back
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - ./docker.env
  client_web:
    build: ./front
    env_file:
      - ./docker.env
    volumes:
      - ./front/src:/usr/vue_app/
      - /usr/vue_app/node_modules
    ports:
      - "8081:8081"
    depends_on:
      - back
  client_mobile:
    build: ./mobile