version: "3.9"
services:
  db:
    image: mariadb:10
    restart: always
    environment:
      - MYSQL_DATABASE=dev
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "33060:3306"
  back:
    build: ./back
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - ./back/docker.env
  front:
    build: ./front
    env_file:
      - ./front/docker.env

    volumes:
      - ./front/src:/usr/vue_app/
      - /usr/vue_app/node_modules
    ports:
      - "8081:8081"
    depends_on:
      - back
