version: "3.9"
services:
  db:
    image: mariadb:10
    restart: always
    environment:
      - MYSQL_DATABASE=dev
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3307:3306"
  back:
    build: ./back
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:password@db:3306/dev
      - PORT=3000
      - SECRET=azertyuiop
  front:
    build: ./front
    environment:
      - VUE_APP_URL=localhost
      - VUE_APP_PORT=3000
    volumes:
      - ./front/src:/usr/vue_app/
      - /usr/vue_app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - back
